= Scheduler.x
zero88
:repo: zero88/scheduler.x
:artifact: io.github.zero88/schedulerx
:sonarKey: zero88_scheduler.x

image:https://github.com/{repo}/actions/workflows/ci.yml/badge.svg[{repo},link=https://github.com/{repo}/actions/workflows/ci.yml]
image:https://img.shields.io/github/v/release/{repo}?sort=semver[GitHub release (latest SemVer)]
image:https://img.shields.io/nexus/r/{artifact}?server=https%3A%2F%2Foss.sonatype.org[Sonatype Nexus (Releases)]
image:https://img.shields.io/nexus/s/{artifact}?server=https%3A%2F%2Foss.sonatype.org[Sonatype Nexus (Snapshots)]

image:https://sonarcloud.io/api/project_badges/measure?project={sonarKey}&metric=ncloc[Lines of Code,link=https://sonarcloud.io/dashboard?id={sonarKey}]
image:https://sonarcloud.io/api/project_badges/measure?project={sonarKey}&metric=coverage[Coverage,link=https://sonarcloud.io/dashboard?id={sonarKey}]
image:https://sonarcloud.io/api/project_badges/measure?project={sonarKey}&metric=sqale_rating[Maintainability Rating,link=https://sonarcloud.io/dashboard?id={sonarKey}]
image:https://sonarcloud.io/api/project_badges/measure?project={sonarKey}&metric=reliability_rating[Reliability Rating,link=https://sonarcloud.io/dashboard?id={sonarKey}]
image:https://sonarcloud.io/api/project_badges/measure?project={sonarKey}&metric=security_rating[Security Rating,link=https://sonarcloud.io/dashboard?id={sonarKey}]
image:https://sonarcloud.io/api/project_badges/measure?project={sonarKey}&metric=alert_status[Quality Gate Status,link=https://sonarcloud.io/dashboard?id={sonarKey}]

A `lightweight plugable scheduler` based on plain https://vertx.io/[Vert.x] core without any external libs for scheduling with _cron-style_ and _interval_ timers with a detail _monitor_ on both sync and async task.

* `Scheduling` with:
* `cron-style` based on http://www.quartz-scheduler.org/[Quartz] - `Unix` cron expression and `timezone` available
on `JVM`
* `interval` with given `time interval`, given `initial delay time` and `repeating` a given number of times or
repeating infinitely
* able to `cancel` schedule event
* Support `synchronize` task and `async` task
* Run on `vertx-worker-thread` or dedicated `vertx thread-pool`
* Monitor `executor event` includes `fire counting`, `fired round`, `event time`, `task result data`, `task error` on
 your need such as `on schedule`, `on misfire`, `on each round`, `on completed`, etc…
* Easy customize your `task` such as `HTTP client job`, `EventBus job`, `MQTT client job`, `database job`, etc…

== Usage

=== Maven Dependency

[source,xml]
----

<dependency>
    <groupId>io.github.zero88</groupId>
    <artifactId>scheduler.x</artifactId>
    <version>1.0.0</version>
</dependency>

----

=== Gradle Dependency

[source,groovy]
----
api("io.github.zero88:schedulerx:1.0.0")

----

== How To

=== Creating an executor

[source,java]
----
IntervalTaskExecutor.builder()
    .vertx(vertx)
    .trigger(IntervalTrigger.builder().interval(1).repeat(10).build())
    .task((jobData, ctx) -> {
        if(ctx.round()==5) {
           ctx.forceStopExecution();
        }
    })
    .build()
    .start()

----

[source,java]
----
CronTaskExecutor.builder()
    .vertx(vertx)
    .trigger(CronTrigger.builder().expression("0/5 * * ? * * *").build())
    .task((jobData, ctx) -> {})
    .build()
    .start(vertx.createSharedWorkerExecutor("TEST_CRON",3));
----

=== Monitor

Please
check https://github.com/zero88/scheduler.x/blob/62d8feb265f45afad2626886c24f2899346f46b1/src/main/java/io/github/zero88/vertx/scheduler/TaskExecutorMonitor.java[TaskExecutorMonitor]
. Example:

[source,java]
----
public interface TaskExecutorLogMonitor extends TaskExecutorMonitor {

    Logger LOGGER = LoggerFactory.getLogger(TaskExecutorLogMonitor.class);
    TaskExecutorMonitor LOG_MONITOR = new TaskExecutorLogMonitor() {};

    @Override
    default void onUnableSchedule(@NotNull TaskResult result) {
        LOGGER.error("Unable schedule task at [{}] due to error", result.unscheduledAt(), result.error());
    }

    @Override
    default void onSchedule(@NotNull TaskResult result) {
        if (result.isReschedule()) {
            LOGGER.debug("TaskExecutor is rescheduled at [{}] round [{}]", result.rescheduledAt(), result.round());
        } else {
            LOGGER.debug("TaskExecutor is available at [{}]", result.availableAt());
        }
    }

    @Override
    default void onMisfire(@NotNull TaskResult result) {
        LOGGER.debug("Misfire tick [{}] at [{}]", result.tick(), result.triggeredAt());
    }

    @Override
    default void onEach(@NotNull TaskResult result) {
        LOGGER.debug("Finish round [{}] - Is Error [{}] | Executed at [{}] - Finished at [{}]", result.round(),
                     result.isError(), result.executedAt(), result.finishedAt());
    }

    @Override
    default void onCompleted(@NotNull TaskResult result) {
        LOGGER.debug("Completed task in round [{}] at [{}]", result.round(), result.completedAt());
    }

}
----

=== Custom task

Please
check https://github.com/zero88/scheduler.x/blob/62d8feb265f45afad2626886c24f2899346f46b1/src/test/java/io/github/zero88/vertx/scheduler/custom/HttpClientTask.java[HttpClientTask]
and
its https://github.com/zero88/scheduler.x/blob/62d8feb265f45afad2626886c24f2899346f46b1/src/test/java/io/github/zero88/vertx/scheduler/custom/HttpClientTaskTest.java[test]
for `async` task

[source,java]
----
public class HttpClientTask implements Task {

    @Override
    public boolean isAsync() {
        return true;
    }

    @Override
    public void execute(@NotNull JobData jobData, @NotNull TaskExecutionContext executionContext) {
        final Vertx vertx = executionContext.vertx();
        JsonObject url = (JsonObject) jobData.get();
        vertx.createHttpClient().request(HttpMethod.GET, url.getString("host"), url.getString("path"), ar1 -> {
            if (ar1.succeeded()) {
                HttpClientRequest request = ar1.result();
                request.send(ar2 -> {
                    if (ar2.succeeded()) {
                        HttpClientResponse response = ar2.result();
                        response.body(ar3 -> {
                            if (ar3.succeeded()) {
                                executionContext.complete(new JsonObject().put("status", response.statusCode())
                                                                          .put("response", ar3.result().toJson()));
                            } else {
                                executionContext.fail(ar3.cause());
                            }
                        });
                    } else {
                        executionContext.fail(ar2.cause());
                    }
                });
            } else {
                executionContext.fail(ar1.cause());
            }
        });
    }

}
----

== TODO

* [ ] Cron task with repeating until a given time / date
* [ ] Async query job data in execution
* [ ] Optimize `CronExpression`

== Disclaim and Disclosure

This is lightweight module then I will not support for adding any rich function like `manage group of task/trigger`
, `publish monitor event` by integrate with a fantastic client such as `Vertx EventBus`, etc… 

I'm planning to do it in `vertx-planner` project later. Stay a tune!!!
