/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 *
 * Detailed information about configuring a multi-project build in Gradle can be found
 * in the user manual at https://docs.gradle.org/7.3.3/userguide/multi_project_builds.html
 */
pluginManagement {
    repositories {
        mavenLocal()
        gradlePluginPortal()
    }
}
val projectName = "schedulerx"
val profile: String by settings
val pools = mutableMapOf(
    projectName to arrayOf(":schedulerx", ":ext"),
    "sample" to emptyArray(),
    "integtest" to emptyArray(),
    "ratelimit" to arrayOf(":ratelimit", ":ratelimit:api"),
)
val docs = arrayOf(":docs")
val ratelimitDocs = arrayOf(":ratelimit:asciidoc")
val excludeCISonar = docs + ratelimitDocs
val excludeCIBuild = pools["sample"]!! + pools["integtest"]!! + excludeCISonar
pools.putAll(
    mapOf(
        "$projectName:docs" to pools[projectName]!!.plus(docs),
        "ratelimit:docs" to pools["ratelimit"]!!.plus(ratelimitDocs)
    )
)

fun flatten(): List<String> = pools.values.toTypedArray().flatten().toSet().toList()

rootProject.name = "$projectName-parent"
val pp = when {
    profile.isBlank() || profile == "all" -> flatten().toTypedArray()
    profile == "ciBuild"                  -> flatten().filter { !excludeCIBuild.contains(it) }.toTypedArray()
    profile == "ciSonar"                  -> flatten().filter { !excludeCISonar.contains(it) }.toTypedArray()
    else                                  -> pools.getOrElse(profile) { throw IllegalArgumentException("Not found profile[$profile]") }
}
pp.forEach { include(it) }
if (pp.contains(":schedulerx")) {
    project(":schedulerx").projectDir = file("core")
}

if (gradle is ExtensionAware) {
    val extensions = (gradle as ExtensionAware).extensions
    extensions.add("BASE_NAME", projectName)
    extensions.add("PROJECT_POOL", pools.toMap())
    extensions.add("SKIP_PUBLISH", excludeCIBuild + arrayOf(":docs", ":sample", ":integtest", ":ratelimit"))
}
