= What scheduler.x helps
:navtitle: What it helps
zero88

A `lightweight plugable scheduler` based on plain https://vertx.io/[Vert.x] core without any external libs for scheduling with _cron-style_ and _interval_ timers with a detail _monitor_ on both sync and async job.

== Overview

* `Scheduling` with:
** `cron-style` based on http://www.quartz-scheduler.org/[Quartz] - `Unix` cron expression and `timezone` available
on `JVM`
** `interval` with given `time interval`, given `initial delay time` and `repeating` a given number of times or
repeating infinitely
* able to `cancel` schedule event
* Support `synchronize` job and `async` job
* Run on `vertx-worker-thread` or dedicated `vertx thread-pool`
* Monitor `executor event` includes `fire counting`, `fired round`, `event time`, `job result data`, `job error` on
your need such as `on schedule`, `on misfire`, `on each round`, `on completed`, etc…
* Easy customize your `job` such as `HTTP client job`, `EventBus job`, `MQTT client job`, `database job`, etc…
